spring:
  h2:
    console:
      enabled: true
      
  datasource:
          url: jdbc:mysql://localhost:3306/springrest
     username: root
     password: pass@word1
     initialization-mode: always
  jpa:    show-sql: true 
    hibernate:      ddl-auto: create