eureka:
  client:
    register-with-eureka: true
server:  port: 8020
spring:
  cloud:
    config:
      uri: http://localhost:8765/  datasource:    url: jdbc:mysql://localhost:3306/springhystrixfeign
    username: root
    password: pass@word1
    